_target_: src.models.liif.LIIF

defaults:
 - optimizer: adam.yaml
 - lr_scheduler: multi_step_lr.yaml
 - architecture@encoder: edsr
 - architecture@inr: mlp

encoder:
  upsampler: null

local_ensemble: true
feat_unfold: true
cell_decode: true