_target_: src.datamodules.DIV2K_datamodule.CelebAHQDataset

data_dir: ${data_dir}/CelebA-HQ  # data_dir is specified in config.yaml

lr_size: 32
hr_size: 256

split_file: ${data_dir}/split.json
first_k: 100

train_dataloader_params:
  batch_size: 16
  num_workers: 0
  pin_memory: False
  shuffle: False

val_dataloader_params:
  batch_size: 16
  num_workers: 0
  pin_memory: False
  shuffle: False

test_dataloader_params:
  batch_size: 1
  num_workers: 0
  pin_memory: False
  shuffle: False

scale_range: [32, 256]

sample_q: 1024